#############
### MY CV ###
#############
repository: mrbende/curriculum-vitae
favicon: images/favicon.ico
version: 2
darkmode: true

### MY INFO
name: Reed Bender
title: Generative AI Engineer // Computational Biologist
email: reedbndr at gmail dot com
website: https://reedbender.com

### SOCIAL
twitter_username: reedbndr
linkedin_username: reed-bender
github_username:  mrbende
instagram_username: reedbendr
youtube_username: '@MindBenderPodcast'

### ABOUT ME
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name is Reed Bender and I am a full-stack engineer with over 7 years of experience specializing in machine learning and cloud engineering for biomedical research. I am currently working as a freelance engineer, building intelligent systems with generative AI to address the needs of research labs and educational platforms.

  My work is driven by the principle of super-exponential growth; I believe that innovation accelerates future innovation, and intelligent systems beget future intelligence. I collaborate closely with teams to develop these technologies, using my proficiency in various languages and frameworks to create impactful, advanced solutions. The things that I currently have the most experience working with are: <mark>Python</mark>, <mark>Docker</mark>, <mark>Nextflow</mark>, <mark>Kubernetes</mark>, <mark>git</mark>, <mark>ChatGPT</mark>, <mark>Langchain</mark>, <mark>HuggingFace</mark>, <mark>AWS</mark>, <mark>Tensorflow</mark>, <mark>Keras</mark>, and <mark>Scanpy</mark>.

content:
  ### PROJECTS
  - title: Projects 
    layout: list
    content:
      - layout: top-middle
        title: Pria
        link: https://hiimpria.ai
        additional_links:
          - title: about-pria
            icon: fas fa-link
            url: https://praxis-ai.com/pria/
        quote: >
          "I asked my class to raise their hand if Pria helped them. Every single hand instantly shot up."
        description: |
          I started this project while consulting with Praxis AI, suggesting we build a Generative AI mentor to go along with their digital course content. I then proceeded to build the **Generative Intelligence Engine**<i class="fas fa-trademark"></i>, which serves as Pria's backend <mark>Flask</mark> server. I was responsible for creating and managing <mark>Gitlab CI/CD</mark> pipelines, deploying the application to a containerized environment in <mark>AWS</mark>, and deploying the production application to a dynamically-scaled and load-balanced <mark>Elastic Container Service</mark>.

          While building this generative AI backend for Pria, I learned how to utilize both <mark>OpenAI</mark>'s LLMs and open-source models via <mark>HuggingFace</mark>, worked with <mark>Langchain</mark> agents and document integration chains, and created custom vector-embedding tools to expand Pria's knowledgebase.
          Pria is now being successfully used by dozens of academic institutions across the country and received two recognitions in the 2023 American Business Awards: *GOLD* for [Achievement in Online Training](https://stevieawards.com/aba/web-awards), and *BRONZE* for [Use of Artificial Intelligence in EdTech](https://stevieawards.com/aba/product-management-new-product-awards).

  ### EXPERIENCE
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Generative AI Engineer at Praxis AI
        link: https://praxis-ai.com/about/
        additional_links:
          - title: alex-ref
            icon: fas fa-user-tie
            url: https://reedbndr.gitlab.io/reed-bender-cv/resources/Feltus-recommendation.png
        caption: September 2022 - December 2023
        description: |
          At Praxis AI, my key contribution was creating the generative AI backend for *Pria* as a LLM-agnostic agent that can source between tools and various language models, manage concurrent users and institutions, and perform Retrieval Augmented Generation on any data provided by users. She combines custom-built literature search tools, <mark>Zapier</mark> web hooks, long-term vector embedding memory in <mark>Pinecone</mark>, image generation with <mark>Stable Diffusion</mark>, and compatibility with ChatGPT plugins.

          Additionally, I created and led a 12-week **[Foundations of AI](https://praxis-ai.com/courses/course-ai-foundations/)** digital course, covering extensive topics from data science to generative AI integrations, which also received a *GOLD* for [K-12 Course or Learning Management Solution](https://stevieawards.com/aba/product-management-new-product-awards) at the 2023 American Business Awards. This course covers everything from introductory statistics and linear algebra to advanced deep learning architectures, culminating in students building a <mark>Transformer</mark> model from scratch.

      - layout: left
        title: Research Associate, Computational Biology / AI at Flagship Labs 84
        link: https://www.flagshippioneering.com/
        additional_links:
          - title: scott-ref
            icon: fas fa-user-tie
            url: https://reedbndr.gitlab.io/reed-bender-cv/resources/Lipnick_recommendation.png
        caption: September 2021 - March 2023
        description: |
          At Flagship Labs 84, an early-stage pharmaceutical startup, I played a crucial role as the first computational biologist tasked with developing advanced computational pipelines and managing cloud infrastructure for single-cell biomedical research.

          My responsibilities included architecting and executing sophisticated data processing pipelines, specifically designed for high-throughput single-cell genomics. Utilizing my Python skills and the <mark>Scanpy</mark> package, combined with expertise in <mark>AWS</mark> cloud architecture, I automated and refined numerous stages of data analysis, ensuring the efficient processing and insightful interpretation of extensive genomic datasets. My expertise was instrumental in configuring and maintaining high-performance cloud-based computational resources appropriate for the computational tasks encountered in cutting-edge biomedical research.

  ### CITATION REFERENCES
  - title: Publications
    layout: list
    content:
      - layout: left
        description: 'Cellular State Transformations Using Deep Learning for Precision Medicine Applications. Colin Targonski*, M. Reed Bender*, et al. September 2020, Cell Patterns. **[Link](https://doi.org/10.1016/j.patter.2020.100087)**'

      - layout: left
        description: 'GEMmaker: process massive RNAseq datasets on heterogeneous computational infrastructure. John A. Hadish, Tyler D. Biggs, Benjamin T. Shealy, M. Reed Bender, et al. May 2022, BMC Bioinformatics. **[Link](https://doi.org/10.1186/s12859-022-04629-7)**'

      - layout: left
        description: 'EdgeCrafting: mining embedded, latent, nonlinear patterns to construct gene relationship networks. Benafsh Husain, M. Reed Bender, Frank Alex Feltus. April 2022, G3. **[Link](https://doi.org/10.1093/g3journal/jkac042)'

      - layout: left
        description: 'Simulating the restoration of normal gene expression from different thyroid cancer stages using deep learning. Nicole M. Nelligan, M. Reed Bender, F. Alex Feltus. June 2022, BMC Cancer. **[Link](https://doi.org/10.1186/s12885-022-09704-z)**'

        description: 'Exploring Lossy Compression of Gene Expression Matrices. Coleman B. McKnight, Alexandra L. Poulos, M. Reed Bender, et al. November 2019, Supercomputing Conference. **[Link](https://ieeexplore.ieee.org/abstract/document/8955120)**'

      - layout: left
        description: 'Our Superconducting Consciousness. Reed Bender. February 2022, Independently Published to Medium. **[Link](https://medium.com/@reedbender/our-superconducing-consciousness-26c9a82072fc)**'

  ### INVITED PRESENTATIONS
  - title: Invited Presentations
    layout: list
    content:
    - layout: top-left
      title: NIH Cancer Moonshot Symposium
      sub_title: Motivations For and Perceptions of Participants Controlling Their Own Data
      caption: September 2019
      description: |
        I presented at the NIH Cancer Moonshot Symposium on Patient Control of Genomic Data for Research and Health in Bethesda, MD. During the seminar, I discussed patient autonomy in managing genomic data records, highlighting the need for increased patient involvement in cancer treatment decisions. **[Link](https://www.youtube.com/watch?v=uj_yCcmgTNI&feature=youtu.be)**

    - layout: top-left
      title: Internet2’s Technology Exchange Conference
      sub_title: Scaling Genomics Workflows with Kubernetes Hybrid Cloud Solutions
      caption: December 2019
      description: |
        At the Internet2’s Technology Exchange Conference in New Orleans, LA, I led a seminar workshop in collaboration with Cisco. The workshop aimed to educate cloud architects and computer engineering professionals about the basics of computational genomics and how to optimize cloud compute architecture for various bioinformatics workflows. **[Link](https://meetings.internet2.edu/2019-technology-exchange/program-guide/tutorials-workshops/)**

    - layout: top-left
      title: Tri-Con Drug Discovery Hackathon
      sub_title: Preclinical Drug Discovery
      caption: March 2020
      description: |
        I led a hackathon team at the Tri-Con Drug Discovery Hackathon in San Francisco, CA. Our goal was to identify precision drugs capable of targeting genetic aberrations in a patient's cancer, specifically focusing on Bill Paseman's case. We presented our team's findings to the hackathon and Tri-Con seminar audience. **[Link](http://rarekidneycancer.org/blog/2020-kidney-cancer-hackathon-results)**

    - layout: top-left
      title: Cisco Container Platform
      sub_title: Accelerating Biological Research with Multicloud Kubernetes
      caption: Cisco Container Platform Case Study
      description: |
        I was interviewed as part of a Cisco marketing video promoting their Cisco Container Platform (CCP). During the interview, I discussed my experience deploying containerized software onto Cisco's cloud platform. **[Link](https://www.cisco.com/c/en/us/products/cloud-systems-management/container-platform/index.html#~case-study)**

  ### EDUCATION
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Clemson University
        sub_title: M.S. in Biomedical Data Science and Informatics
        caption: September 2019 - May 2021
        description: |
          During my graduate research at Clemson University with Dr. Alex Feltus in the Genetics and Biochemistry Department, I focused on scaling bioinformatics workflows for cancer genomics. This involved optimizing pipelines on Kubernetes and Google Cloud for efficient analysis of large genomic datasets. I also trained undergraduate researchers and presented at the NIH Cancer Moonshot Symposium and Internet2's Technology Exchange Conference.

          I'm proficient in Python, R, Bash, and orchestration tools like AWS, Docker, Nextflow, Kubernetes, GCP, and Cisco Container Platform. In my undergraduate research, I integrated patient-specific RNA-seq data into public datasets, applied deep learning for gene expression analysis, and co-authored publications, contributing to precision medicine in cancer.

      - layout: top-right
        title: Clemson University
        sub_title: B.S. in Bioengineering
        caption: September 2016 - May 2020
        description: |
          I completed my Bachelor of Science in Bioengineering with a concentration in Biomaterials and a minor in Genetics, graduating from the Clemson Honors College. My tenure in Dr. Alex Feltus' bioinformatics research lab began as a Junior in 2018, and continued through my masters program until graduating in 2021.

### BUILD
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
 - jekyll-seo-tag
