# Site
repository: mrbende/curriculum-vitae
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Reed Bender
title: Generative AI Engineer // Computational Biologist
email: reedbndr@gmail.com
website: www.reedbender.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: reedbndr
github_username: mrbende

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hi, I'm Reed Bender, a passionate Bioengineering and Biomedical Data Science & Informatics professional. My expertise lies in Generative AI Engineering and Computational Biology. I have a strong background in both academia and industry, with a focus on developing and applying AI-driven solutions in the biomedical field. 

  I am skilled in technologies like OpenAI, Langchain, Stable Diffusion, Zapier, Python, Docker, AWS, Flask, GitLab C/I, Pinecone, and more.

content:
  - title: Engineering Experience
    layout: list
    content:
      - layout: top-middle
        title: Generative AI Engineer at Praxis AI
        link: praxis-ai.com/about/
        description: |
          As a Generative AI Engineer at Praxis AI, I've been instrumental in developing the AI-powered virtual mentor "Pria", which leverages Langchain agents and GPT-4. I have also taught a 12-week AI course and contributed to Praxis AI's numerous accolades.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Clemson University
        caption: September 2016 - May 2021
        sub_title: M.S. in Biomedical Data Science and Informatics, B.S. in Bioengineering
        description: |
          At Clemson University, I pursued a dual degree in Bioengineering (B.S.) and Biomedical Data Science and Informatics (M.S.). I focused on biomaterials, genetics, and was part of the Clemson Honors College.

  - title: A Little More About Me
    layout: text
    content: |
      In addition to my professional interests, I am passionate about yoga, breathwork, and biohacking. I am also a certified Yoga and Breathwork Instructor. I enjoy exploring new technologies and applying them to solve complex problems in the biomedical field.

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
