name: Generate PDF CV

on:
  push:
    branches:
      - main # Adjust this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex

    - name: Convert CV to PDF
      run: |
        pandoc -o cv.pdf cv.md 
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: cv
        path: cv.pdf
